services:

  db:
    image: postgres:15
    container_name: energy-db
    environment:
      POSTGRES_DB:       energy_db
      POSTGRES_USER:     energy_user
      POSTGRES_PASSWORD: energy_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - energy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U energy_user -d energy_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    container_name: energy-gateway
    ports:
      - "8080:8080"
    networks:
      - energy-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=energy_db
      - DB_USER=energy_user
      - DB_PASSWORD=energy_pass

  sensor:
    build:
      context: ./Embedded
      dockerfile: Dockerfile
    container_name: energy-sensor
    command: ["./temp_sensor", "TEMP_A", "Zone_A", "22.0", "5"]
    depends_on:
      - gateway
    networks:
      - energy-network
    restart: unless-stopped
    environment:
      - GATEWAY_HOST=gateway

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: energy-backend
    ports:
      - "8081:8081"
    networks:
      - energy-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=energy_db
      - DB_USER=energy_user
      - DB_PASSWORD=energy_pass
      - JWT_SECRET=energy-monitoring-super-secret-key-change-in-production
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres_data:

networks:
  energy-network:
    driver: bridge
